# Generated by Django 3.0.8 on 2020-07-18 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200716_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Profile'),
        ),
    ]
