# Generated by Django 3.0.8 on 2020-07-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200718_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_regsitered',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
