# Generated by Django 3.0.8 on 2020-07-20 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_profile_date_regsitered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_regsitered',
            new_name='date_registered',
        ),
    ]
