# Generated by Django 3.0.8 on 2020-07-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200728_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='repeat',
            field=models.CharField(choices=[('1', 'Never'), ('2', 'Daily'), ('3', 'Weekly'), ('4', 'Monthly'), ('5', 'Yearly')], default='Choose Repetition', max_length=50),
        ),
    ]
